config/routes.rb
Rails.application.routes.draw do
  root 'images#home'
  get  '/user_images_index',    to: 'images#user_images_index'
  get  '/keyword_images_index', to: 'images#keyword_images_index'
  post '/batch_download',       to: 'images#batch_download'
  get  '/individ_download',     to: 'images#individ_download'
  get  '/send_zip_to_client',   to: 'images#send_zip_to_client'
  get  '/send_image_to_client', to: 'images#send_image_to_client'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/tweet_model.rb
class TweetModel
    include ActiveModel::Model
    
    require 'fileutils'
    require 'open-uri'
    require 'zip'
    
    attr_accessor :id, :keyword, :images, :user_info, :tweets_info, :result_type
    
    GET_USER_TWEETS_MAX_COUNT  = 200
    GET_KEYWORD_TWEETS_MAX_COUNT  = 100
    SAVE_IMAGES_ROOT_DIR  = "/tmp/twimagetter/"
    SLASH                 = "/"
    EXTENSION_ZIP         = "\.zip"
    
    def initialize(args={})
      @id = args[:id] || ""
      @keyword = args[:keyword] || ""
      @images = args[:images] || []
      @user_info = {}
      @tweets_info = []
      @result_type = args[:result_type] || "recent"
    end
    
    def search_user_images
      get_user_info
      get_user_images
    end
    
    def search_keyword_images
      get_keyword_images
    end
    
    def download_to_server
      save_images_dir_path = create_dir
      save save_images_dir_path
      output_zip_name = create_zip save_images_dir_path
      FileUtils.rm_rf save_images_dir_path
      return output_zip_name
    end
    
    private
      
      def client
        @client ||= Twitter::REST::Client.new do |config| 
          config.consumer_key = Rails.application.secrets.user_consumer_key
          config.consumer_secret = Rails.application.secrets.user_consumer_secret
          config.bearer_token = Rails.application.secrets.user_bearer_token
        end
      end

      def get_user_info
        self.user_info = extract_user_info raw_user_info
      end
      
      def raw_user_info
        client.user(self.id)
      end
    
      def extract_user_info(raw_user_info)
        { "name" => raw_user_info.name,
          "description" => raw_user_info.description,
          "url" => raw_user_info.url.to_s,
          "profile_image_url" => raw_user_info.profile_image_url.to_s
        }
      end
      
      def get_user_images
        extract_images user_tweets
      end
    
      def user_tweets
        collect_with_max_id do |max_id|
          options = {count: GET_USER_TWEETS_MAX_COUNT, include_rts: false}
          options[:max_id] = max_id unless max_id.nil?
          client.user_timeline(self.id, options)
        end
      end
      
      def collect_with_max_id(collection=[], max_id=nil, &block)
        response = yield(max_id)
        collection += response
        response.empty? ? collection.flatten : collect_with_max_id(collection, response.last.id - 1, &block)
      end
      
      def get_keyword_images
        extract_images keyword_tweets
      end
      
      def keyword_tweets
        client.search(self.keyword, keyword_search_options).take(1500)
      end
      
      def keyword_search_options
        {result_type: self.result_type, filter: "images", exclude: "retweets"}
      end
      
      def extract_images(tweets)
        tweets.each do |tweet|
          get_image_url(tweet)
        end
      end
      
      def get_image_url(tweet)
        if tweet.media.any?
          tweet.media.each do |media|
            self.images << get_media_url(media)
            self.tweets_info << extract_tweet_info(tweet)
          end
        end
      end
      
      def get_media_url(media)
        media.media_url.to_s
      end
      
      def extract_tweet_info(tweet)
        { "user" => tweet.user.screen_name.to_s,
          "id"   => tweet.id.to_s
        }
      end
      
      def create_dir
        now = Time.now
        dir_path = SAVE_IMAGES_ROOT_DIR + now.strftime("%Y%m%d%H%M%S") + now.usec.to_s + SLASH
        FileUtils.mkdir_p(dir_path)
        return dir_path
      end
      
      def save(save_images_dir_path)
        self.images.each do |image|
          output_file_name = save_images_dir_path + File.basename(image)
          open(output_file_name, 'wb') do |output|
            open(image) do |data|
              output.write(data.read)
            end
          end
        end
      end
      
      def create_zip(save_images_dir_path)
        output_zip_name = SAVE_IMAGES_ROOT_DIR + (self.id.blank? ? self.id : (self.id + "_")) + (self.keyword.blank? ? self.keyword : (self.keyword + "_")) + File.basename(save_images_dir_path) + EXTENSION_ZIP
        entries = Dir.entries(save_images_dir_path) - %w(. ..)
        ::Zip::File.open(output_zip_name, ::Zip::File::CREATE) do |io|
          write_entries entries, '', io, save_images_dir_path
        end
        return output_zip_name
      end
      
      def write_entries(entries, path, io, input_dir)
        entries.each do |e|
          zip_file_path = path == '' ? e : File.join(path, e)
          disk_file_path = File.join(input_dir, zip_file_path)
          if File.directory? disk_file_path
            recursively_deflate_directory(disk_file_path, io, zip_file_path)
          else
            put_into_archive(disk_file_path, io, zip_file_path)
          end
        end
      end
      
      def recursively_deflate_directory(disk_file_path, io, zip_file_path)
        io.mkdir zip_file_path
        subdir = Dir.entries(disk_file_path) - %w(. ..)
        write_entries subdir, zip_file_path, io
      end
      
      def put_into_archive(disk_file_path, io, zip_file_path)
        io.get_output_stream(zip_file_path) do |f|
          f.write(File.open(disk_file_path, 'rb').read)
        end
      end
      
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/images_controller.rb
class ImagesController < ApplicationController
  
  require 'open-uri'

  def home
    @tweet ||= TweetModel.new
  end
  
  def user_images_index
    @tweet ||= TweetModel.new(id: params[:id])
    begin
      @tweet.search_user_images
      render "index"
    rescue Twitter::Error::NotFound
      flash[:danger] = "Your search user does not exist"
      redirect_to root_url
    end
  end
  
  def keyword_images_index
    @tweet ||= TweetModel.new(keyword: params[:keyword], result_type: params[:result_type])
    @tweet.search_keyword_images
    render "index"
  end
  
  def batch_download
    @tweet ||= TweetModel.new(tweet_params)
    @send_zip_to_client_url = send_zip_to_client_path(:zip => @tweet.download_to_server)
    render :partial => "send_zip_to_client"
  end
  
  def individ_download
    @send_image_to_client_url = send_image_to_client_path(:image => params[:image])
    render :partial => "send_image_to_client"
  end
  
  def send_zip_to_client
    send_zip params[:zip]
  end
  
  def send_image_to_client
    send_image params[:image]
  end
  
  private
  
    def tweet_params
      params.require(:tweet_model).permit(:id, :keyword, images: [])
    end
    
    def send_zip(zip)
      send_file(zip, :filename => File.basename(zip), :type => 'application/zip', :disposition => 'attachment', :x_sendfile => true)
    end
    
    def send_image(image)
      open(image) do |f|
        send_data(f.read, :filename => File.basename(image), :disposition => 'attachment')
      end
    end
    
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/images_helper.rb
module ImagesHelper
    def comp_commercial_at(text)
        text[0] == '@' ? text : '@' + text
    end
    
    def tweet_url(tweet_info)
        'https://twitter.com/' + tweet_info["user"] + '/status/' + tweet_info["id"]
    end
end

app/views/images/_send_image_to_client.js.erb
window.location.href = "<%= @send_image_to_client_url %>";

app/views/images/_send_zip_to_client.js.erb
window.location.href = "<%= @send_zip_to_client_url %>";
$('#loading_image').hide();

app/views/images/home.html.erb
<div class="content">
    <div class="row">
        <h1>TwImaGetter</h1>
            <div class="main">
                <div class="subscribe">
                    <h2>Let's get your favorite images from Twitter</h2>
                    <br>
                    <div class="form">
                        <% flash.each do |message_type, message| %>
                            <%= content_tag(:div, message, class: "alert alert-#{message_type}") %>
                        <% end %>
                        <%= image_tag('user_search_icon.png') %>
                        <label class="user_search_label">User tweet images</label>
                        <%= form_for @tweet, url: user_images_index_path, html: { method: "GET", enforce_utf8: false } do |f| %>
                            <input name="id" type="text" id="tweet_model_id" placeholder="UserId" required="">
                            <%= f.submit "UserSearch", name: nil %>
                        <% end %>
                    </div>
                    <hr>
                    <div class="form">
                        <%= form_for @tweet, url: keyword_images_index_path, html: { method: "GET", enforce_utf8: false } do |f| %>
                            <%= image_tag('keyword_search_icon.png') %>
                            <label class="keyword_search_label">Keyword search Images</label><br>
                            <input name="keyword" type="text" id="tweet_model_keyword" placeholder="Keyword" required="">
                            <%= f.submit "KeywordSearch", name: nil %>
                            <%= radio_button_tag 'result_type', 'recent', true %>
                            <label class="result_type_radio_button_label">recent</label>
                            <%= radio_button_tag 'result_type', 'popular', false %>
                            <label class="result_type_radio_button_label">popular</label>
                            <%= radio_button_tag 'result_type', 'mixed', false %>
                            <label class="result_type_radio_button_label">mixed(recent+popular)</label>
                        <% end %>
                    </div>
                </div>
            </div>
        <p class="copy_rights">&copy; 2016 Coming Soon Widget. All Rights Reserved | Design by  <a href="http://w3layouts.com/"> W3layouts</a></p>
    </div>
</div>

app/views/images/index.html.erb
<div class="container">
    <div class="row">
        <div class="col-lg-12">
            <h1 class="page-header"><%= !@tweet.id.blank? ? comp_commercial_at(@tweet.id) : @tweet.keyword %> | Search Result </h1>
            <% if !@tweet.id.blank? %>
                <label class="userinfo_title">User Profile</label>
                <div class="userinfo">
                    <%= link_to image_tag(@tweet.user_info["profile_image_url"]), @tweet.user_info["url"], :target => ["_blank"] %>
                    <%= link_to @tweet.user_info["name"], @tweet.user_info["url"], :target => ["_blank"], class: "userinfo_name" %>
                    <br>
                    <%= link_to (comp_commercial_at(@tweet.id)), @tweet.user_info["url"], :target => ["_blank"], class: "userinfo_id" %>
                    <br>
                    <div class="userinfo_description">
                        <%= raw Rinku.auto_link(h(@tweet.user_info["description"])) %>
                    </div>
                </div>
                <hr>
            <% end %>

            <%= form_for @tweet, url: batch_download_path, remote: true, html: { enforce_utf8: false } do |f| %>
                <%= f.hidden_field :id, value: @tweet.id %>
                <%= f.hidden_field :keyword, value: @tweet.keyword %> 
                <%= f.submit "Download",name: nil, data: { disable_with: "Now Downloading..." }, id: "submit_download", class: "btn btn-primary" %>
                <%= image_tag('loading.png', :id => "loading_image") %>
                <div class="select_all">
                    <input type="checkbox" id="images_all" name="images_all">
                    <label for="images_all" class="images_all_label">select all</label>
                    <label for="images_all" class="select_count"></label>
                </div>
                <div id="images_area">
                    <% @tweet.images.zip(@tweet.tweets_info).each do |image, tweet_info| %>
                        <label>
                            <%= f.check_box :images, { class: "checkbox", multiple: true, :checked => false, include_hidden: false }, image %>
  　                         <%= image_tag(image, :class => "search_image") %>
  　                         <%= link_to image_tag('link_icon.png'), tweet_url(tweet_info), :target => ["_blank"], :class => "tweet_link" %>
  　                         <%= link_to image_tag('new_window_icon.png'), image, :target => ["_blank"], :class => "image_link" %>
  　                         <%= link_to image_tag('download_icon.png'), individ_download_path(:image => image), :class => "download_link", :remote => true %>
                        </label>
                    <% end %>
                </div>
            <% end %>
        </div>
    </div>
</div>

<hr>

<!-- Footer -->
<footer>
    <div class="row">
        <div class="col-lg-12">
            <p class="copy_rights">Copyright &copy; Your Website 2014</p>
        </div>
    </div>
</footer>
<br>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
  <title>TwImaGetter</title>
  <%= stylesheet_link_tag 'manifest.css', media: 'all' %>
  <link href='//fonts.googleapis.com/css?family=Audiowide' rel='stylesheet' type='text/css'>
  <link href='//fonts.googleapis.com/css?family=Montserrat:400,700' rel='stylesheet' type='text/css'>
  <link href='//fonts.googleapis.com/css?family=Open+Sans:400,300,300italic,400italic,600,600italic,700,700italic,800,800italic' rel='stylesheet' type='text/css'>
  <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  <%= csrf_meta_tags %>
  </head>
  <body>
    <!-- Navigation -->
    <nav class="navbar navbar-inverse navbar-fixed-top" role="navigation">
        <div class="container">
            <!-- Brand and toggle get grouped for better mobile display -->
            <div class="navbar-header">
              <%= link_to "TwImaGetter", root_path, id: "navbar-brand" %>
            </div>
            <!-- /.navbar-collapse -->
        </div>
        <!-- /.container -->
    </nav>
    <%= yield %>
  </body>
</html>